tailwind.config = {
    darkMode: "class",
    theme: {
        extend: {
            "colors": {
                "on-tertiary-fixed": "#211a18",
                "error-container": "#ffdad6",
                "on-error-container": "#93000a",
                "bg-input": "#F0F0EF",
                "background": "#fcf8f8",
                "surface-variant": "#e5e2e1",
                "secondary-container": "#ffbb83",
                "primary-container": "#26282b",
                "secondary": "#855323",
                "on-surface": "#1c1b1c",
                "outline-variant": "#c5c6ca",
                "outline": "#75777b",
                "on-secondary-container": "#79491a",
                "surface-container-high": "#ebe7e7",
                "tertiary-fixed-dim": "#d1c3c0",
                "tertiary": "#191210",
                "surface-container-highest": "#e5e2e1",
                "secondary-fixed-dim": "#fcb980",
                "surface-dim": "#ddd9d9",
                "on-secondary-fixed": "#2e1500",
                "on-secondary-fixed-variant": "#693c0d",
                "tertiary-fixed": "#eedfdc",
                "primary-fixed-dim": "#c6c6ca",
                "text-secondary": "#6E6E6E",
                "primary": "#111416",
                "on-primary-fixed": "#1a1c1f",
                "on-primary": "#ffffff",
                "surface-tint": "#5d5e62",
                "surface": "#fcf8f8",
                "on-error": "#ffffff",
                "surface-bright": "#fcf8f8",
                "primary-fixed": "#e2e2e6",
                "on-background": "#1c1b1c",
                "bg-secondary": "#F4F4F3",
                "text-primary": "#2B2B2B",
                "inverse-surface": "#313030",
                "on-tertiary": "#ffffff",
                "secondary-fixed": "#ffdcc2",
                "text-muted": "#9A9A9A",
                "on-secondary": "#ffffff",
                "on-surface-variant": "#45474a",
                "tertiary-container": "#2e2624",
                "inverse-on-surface": "#f4f0ef",
                "bg-card-alt": "#F1F1EF",
                "surface-container": "#f1eded",
                "border-light": "#E3E3E1",
                "bg-primary": "#FFFFFF",
                "on-tertiary-fixed-variant": "#4e4542",
                "on-primary-fixed-variant": "#45474a",
                "inverse-primary": "#c6c6ca",
                "accent-blue": "#4C6E9E",
                "surface-container-lowest": "#ffffff",
                "on-tertiary-container": "#988c89",
                "error": "#ba1a1a",
                "tag-bg": "#EFEFED",
                "surface-container-low": "#f6f3f2"
            },
            "borderRadius": {
                "DEFAULT": "0.25rem",
                "lg": "0.5rem",
                "xl": "0.75rem",
                "full": "9999px"
            },
            "spacing": {
                "gutter": "1.5rem",
                "card-padding": "1.5rem",
                "section-gap": "5rem",
                "container-padding": "2rem"
            },
            "fontFamily": {
                "display-script": ["Sacramento"],
                "body-main": ["Inter"],
                "display-light": ["Plus Jakarta Sans"],
                "headline-card": ["Inter"],
                "headline-hero": ["Inter"],
                "label-pill": ["Inter"],
                "display-light-mobile": ["Plus Jakarta Sans"],
                "headline-hero-mobile": ["Inter"]
            },
            "fontSize": {
                "display-script": ["80px", {"lineHeight": "1.1", "fontWeight": "400"}],
                "body-main": ["16px", {"lineHeight": "1.6", "fontWeight": "400"}],
                "display-light": ["52px", {"lineHeight": "1.2", "letterSpacing": "0.05em", "fontWeight": "300"}],
                "headline-card": ["20px", {"lineHeight": "1.4", "fontWeight": "600"}],
                "headline-hero": ["68px", {"lineHeight": "1.1", "fontWeight": "700"}],
                "label-pill": ["13px", {"lineHeight": "1", "fontWeight": "500"}],
                "display-light-mobile": ["36px", {"lineHeight": "1.2", "fontWeight": "300"}],
                "headline-hero-mobile": ["42px", {"lineHeight": "1.2", "fontWeight": "700"}]
            }
        },
    },
}
